### ISSUE TITLE
Future request (if possible) - notify if X days old

### ISSUE THREAD

**Issue by RichardTheuws** [josemonkey/freezer-inventory-example#1]
Thank you so much for sharing the script! I'm a novice at coding myself, but I know how to C/P so got it to work :)

What I'd love to add (if I knew how to haha) is a way to send out a notification (by mail would be great already) if an item reaches a certain age (in days, that is). My freezer is quite large and I tend to always forget to take SOME stuff out in time.

**Comment by RichardTheuws** [comment]
Got it to work with this code I found online, feel free to use (just added it at the bottom of the script). You could also add a trigger to get this function to check every day/week/month, but I haven't done that yet.

edit: I do get some error when I run the script now, but it still works.

```
function checkAgeOfProducts() {
  // Load the sheet that contains the birthdays.
  let inventorySheet = getDataSheet_();

  // Get the last row in the sheet that has data.
  var numRows = inventorySheet.getLastRow();

  // Load data in the first two columns from the second row till the last row. 
  // Remember: The first row has column headers so we don’t want to load it.
  var range = inventorySheet.getRange(5, 1, numRows - 1, 5).getValues();

  // Use a for loop to process each row of data
  for(var index in range) {

    // For each row, get the product description, ID and age
    var row = range[index];
    var number =row[0];
    var name = row[1];
    var age = row[4];

    // Check if the product is older than X days (change the '89' to your number)
    if(age > 89) {
      //If yes, send an email reminder
      emailReminder(name,age,number);
    }
  }
}


// Function to send the email reminder
function emailReminder(name,age,number) {
  var subject = "It's time to eat " + name;
  var recipient = "your@emailaddress.com"
  var body = name + "(" + number + ") is " + age + " days old.";
  MailApp.sendEmail(recipient, subject, body);
}
```

**Comment by RichardTheuws** [comment]
(added a trigger via Google scripts to run this part of the script every week on a certain day and time)

**Comment by josemonkey** [comment]
Thanks for this - it's such a good idea. I haven't used triggers on app scripts before, so I appreciate you telling me about that!

I may try to incorporate something like this when I make some other updates I'm thinking about.

**Comment by RichardTheuws** [comment]
Trigger works perfectly, got some mails this morning telling me which products I need to use soon :)

Another update I was thinking about (and trying to build) is adding the description to the "Item removed" notification, just as a double check. Was trying to use the code from the script above but didn't get far today :)

**Comment by josemonkey** [comment]
I have been thinking about exactly same thing. I think what I really want to do is have the initial call just be a lookup of the item to retrieve the info, then require a confirmation from the user, then execute a second call once the person confirms it's the right item to remove.

To do that, I think I probably want to make the Siri Shortcut smart enough to understand a more complex response - so it can tell the difference between a successful item lookup and a failure. I have ideas about how I would do it, but I haven't had time to implement it just yet. (I'm in the middle of a pretty intense content production schedule right now, but I should free up in a few days.)

**Comment by josemonkey** [comment]
Just wanted to let you know I implemented something like this just now. I chose to do a periodic digest instead of one email per item, and I got fancy and used an HTML template to make the emails look nice (because I'm extra, lol). Thanks again for the suggestion and the code example.
