### ISSUE TITLE
A different take.. kind of.

### ISSUE THREAD

**Issue by Critter** [josemonkey/freezer-inventory-example#2]
Hey Jose - 

I took your idea and paired it with [Data Jar](https://apps.apple.com/us/app/data-jar/id1453273600) instead of using a server.  Data Jar is a free download, and often used as a "database" for shortcuts

To run this shortcut, you only need to have Data Jar installed. The shortcut will create the necessary store for the inventory. It's not fully fleshed out.. there are some other things that can be done, but I thought I'd share it with you. Some different ways to do some things...
also Data Jar will sync between all your devices, Mac included..

Let me know what you think..

https://www.icloud.com/shortcuts/6a0058047c484b3e8f2a92e74ffb7239

**Comment by josemonkey** [comment]
That's a cool idea. I like that people are adapting this to their needs and preferences.
